### ISSUE TITLE
Not fit after long words  wrapping to new line

### ISSUE THREAD

**Issue by FlashTang** [wwf410918701/react-textarea-auto-witdth-height#2]
![Screenshot 2024-03-29 at 00 04 27](https://github.com/wwf410918701/react-textarea-auto-witdth-height/assets/920751/67e3f7fe-33c0-4ec1-a3c2-17810d948f65)

Hello sir
try type "this is so greeeeeeeeeeeeeeeeeet"
there is blank space in the right side , is there a way to fix this?

in iOS native - UITextView , sizeThatFits function 
if you call  sizeThatFits of UITextView ,  the width will reduce to fit (aka no blank space in the right side)
```
let textView = UITextViewX()
addSubview(textView)
textView.text = "this is so greeeeeeeeeeeeeeeeeeeat"
let size = textView.sizeThatFits(CGSize(width: 100, height: CGFloat.greatestFiniteMagnitude))
textView.frame.size = size
```

![IMG_3276(20240329-005352)](https://github.com/wwf410918701/react-textarea-auto-witdth-height/assets/920751/055a3964-7d43-4345-bf38-22480214c269)
![IMG_3275(20240329-005337)](https://github.com/wwf410918701/react-textarea-auto-witdth-height/assets/920751/57d501f7-255d-4d00-b45f-796aa098769e)

I was looking for the same solution with native UITextView  in html textarea , but I found nothing in whole internet

I made a pure js  html version ,it's simple, but unfortunately it has the same behavior with the “react-textarea-auto-witdth-height” 

```
<!DOCTYPE html>
<html>
<script>

    function auto_grow(element, max) {
        element.style.maxWidth = max + "px";
         element.style.width = "auto";
        element.style.whiteSpace = "nowrap";
        element.style.width = element.scrollWidth + "px";

        if (element.scrollWidth >= max) {
            element.style.whiteSpace = "pre-line";
        }

        element.style.height = "auto";
        element.style.height = element.scrollHeight + "px";
    }

</script>

<body>

    <textarea style="resize: none;min-width: 50px;min-height: 0px;" rows="1" cols="1" oninput="auto_grow(this,150)"></textarea>

</body>
</html>
```

**Comment by wwf410918701** [comment]
The aim of the component is to provide a `Textarea` that has the exact same behaviour in its size size as `div`, so this is actually intended. But feel free to explore any css option to achieve your need.😄
